import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Terms of Service — Walter",
  description: "Terms and conditions for using Walter travel planning services.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-page-bg">
      <Navbar />

      <main className="max-w-3xl mx-auto px-6 py-16">
        <div className="card-base p-8">
          <h1 className="font-semibold text-[28px] text-gray-dark mb-4">
            Terms of Service
          </h1>
          <p className="text-on-light-tertiary text-sm mb-12">
            Last updated: April 2, 2026
          </p>

          <div className="space-y-10 text-on-light-secondary leading-relaxed">
            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using Walter (&quot;the Service&quot;), you agree
                to be bound by these Terms of Service. If you do not agree to
                these terms, do not use the Service. Walter reserves the right to
                modify these terms at any time, and your continued use constitutes
                acceptance of any changes.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                2. Service Description
              </h2>
              <p>
                Walter is an AI-powered travel planning platform. Users complete a
                quiz describing their travel preferences, and Walter generates
                personalized itineraries with flights, hotels, activities, and
                restaurants. The platform provides affiliate links to third-party
                booking services where users can complete their reservations.
                Walter does not directly process bookings, payments, or
                reservations.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                3. Affiliate Disclosure
              </h2>
              <p>
                Walter earns commissions through affiliate partnerships with
                travel booking services including, but not limited to, Skyscanner
                and Booking.com. When you click a link on Walter and complete a
                booking on a partner site, Walter may receive a commission at no
                additional cost to you. These commissions help us keep the service
                free. Affiliate relationships do not influence the order or
                selection of recommendations, which are generated by AI based
                solely on your stated preferences.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                4. User Responsibilities
              </h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  You must provide accurate information in the travel planning
                  quiz to receive relevant recommendations.
                </li>
                <li>
                  You are responsible for verifying all travel details (dates,
                  prices, availability, visa requirements, travel advisories)
                  before making any bookings.
                </li>
                <li>
                  You must not use the Service for any unlawful purpose or in
                  violation of any applicable laws.
                </li>
                <li>
                  You must not attempt to reverse-engineer, scrape, or interfere
                  with the Service or its infrastructure.
                </li>
                <li>
                  If you create an account, you are responsible for maintaining
                  the confidentiality of your login credentials.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                5. Accuracy of Information
              </h2>
              <p>
                Walter uses AI and third-party data sources to generate travel
                recommendations. While we strive for accuracy, we do not guarantee
                that prices, availability, schedules, or other travel information
                displayed on the platform are accurate, complete, or current.
                Prices and availability are subject to change and are determined
                by third-party booking partners. Always verify details directly
                with the booking provider before finalizing any travel plans.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                6. Intellectual Property
              </h2>
              <p>
                All content, features, and functionality of the Service --
                including text, graphics, logos, icons, the Walter brand, AI
                models, and software -- are the exclusive property of Walter
                Travel, Inc. and are protected by copyright, trademark, and other
                intellectual property laws. You may share generated itineraries
                for personal use but may not reproduce, distribute, or create
                derivative works from the Service for commercial purposes without
                our written consent.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                7. User Content
              </h2>
              <p>
                By submitting quiz responses and other information to Walter, you
                grant us a non-exclusive, worldwide, royalty-free license to use,
                process, and analyze that data to provide and improve the Service.
                We may use aggregated, anonymized data for analytics and AI model
                training. You retain ownership of any personal information you
                provide, subject to the rights granted herein.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                8. Third-Party Services
              </h2>
              <p>
                The Service contains links to third-party websites and booking
                platforms. Walter is not responsible for the content, privacy
                policies, or practices of any third-party sites. When you leave
                Walter to visit a partner booking site, you are subject to that
                site&apos;s terms and conditions. We encourage you to review the
                terms of any third-party service before completing a transaction.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                9. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by law, Walter Travel, Inc. and
                its officers, directors, employees, and agents shall not be liable
                for any indirect, incidental, special, consequential, or punitive
                damages arising from your use of the Service. This includes, but
                is not limited to, damages resulting from inaccurate travel
                recommendations, missed flights, booking errors on third-party
                platforms, or any other travel-related issues. Our total liability
                for any claim shall not exceed the amount you paid to Walter in
                the twelve months preceding the claim, if any.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                10. Disclaimer of Warranties
              </h2>
              <p>
                The Service is provided &quot;as is&quot; and &quot;as
                available&quot; without warranties of any kind, whether express or
                implied. We disclaim all warranties including, but not limited to,
                implied warranties of merchantability, fitness for a particular
                purpose, and non-infringement. We do not warrant that the Service
                will be uninterrupted, error-free, or that any defects will be
                corrected.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                11. Indemnification
              </h2>
              <p>
                You agree to indemnify and hold harmless Walter Travel, Inc. from
                any claims, damages, losses, or expenses (including reasonable
                attorney fees) arising from your use of the Service, your
                violation of these Terms, or your violation of any rights of a
                third party.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                12. Termination
              </h2>
              <p>
                We reserve the right to suspend or terminate your access to the
                Service at any time, with or without cause, and with or without
                notice. Upon termination, your right to use the Service ceases
                immediately. Provisions that by their nature should survive
                termination shall remain in effect.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                13. Governing Law
              </h2>
              <p>
                These Terms shall be governed by and construed in accordance with
                the laws of the State of Delaware, United States, without regard
                to conflict of law principles. Any disputes arising under these
                Terms shall be resolved in the state or federal courts located in
                Delaware.
              </p>
            </section>

            <section>
              <h2 className="font-semibold text-[21px] text-gray-dark mb-3">
                14. Contact Us
              </h2>
              <p>
                If you have questions about these Terms of Service, please contact
                us at{" "}
                <a
                  href="mailto:legal@scoutie.com"
                  className="text-accent hover:text-accent-light"
                >
                  legal@scoutie.com
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}
